[pipeline]
pipeline_name = "taxi_pipeline_new"
dataset_name = "new_taxi_data"

[destination.bigquery]
location = "US"

[destination.bigquery.credentials]
project_id = "datazoomcamp-486715"
path = "C:/Users/user/Documents/data-engineering-bootcampV2/dlt-Hub/credentials/DESTINATION__BIGQUERY__CREDENTIAL.json"