# BigQuery credentials
[destination.bigquery]
location = "US"

[destination.bigquery.credentials]
project_id = "datazoomcamp-486715"
path = "C:/Users/user/Documents/data-engineering-bootcampV2/dlt-Hub/credentials/DESTINATION__BIGQUERY__CREDENTIAL.json"

# filesystem config
[destination.filesystem]
bucket_url = "C:/Users/user/Documents/data-engineering-bootcampV2/dlt-Hub/storage"
layout = "{table_name}/{load_id}.{file_id}.{ext}"