# BigQuery credentials
[destination.bigquery.credentials]

project_id = "datazoomcamp-486715"
path = "../credentials/DESTINATION__BIGQUERY__CREDENTIAL.json"

# filesystem config
[destination.filesystem]
bucket_url="storage"